name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_SRV_URL: "${{ secrets.VITE_SRV_URL }}"
      VITE_SRV_WS: "${{ secrets.VITE_SRV_WS }}"

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: mkdir "$HOME/.ssh" 
      - run: echo "${{ secrets.VPS_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      - run: echo "StrictHostKeyChecking no" >> "$HOME/.ssh/config"
      # Build
      - run: VITE_SRV_URL=$VITE_SRV_URL VITE_SRV_WS=$VITE_SRV_WS npm ci && npm run build
      # Deploy
      - run: cd dist && rsync -e "ssh -p 54853 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@45.9.72.39:/var/www/html/
      - run: cd openfleet-back && rsync -e "ssh -p 54853 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress . root@45.9.72.39:/var/www/openfleet-node
      - run: cd openfleet-back && rsync -e "ssh -p 54853 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress ./package.json root@45.9.72.39:/var/www/openfleet-node
      - run: ssh -p 54853 -i $HOME/.ssh/key -o StrictHostKeyChecking=no root@45.9.72.39 'cd /var/www/openfleet-node && npm install'